const express = require("express");
const { createBillBoard, getBillBoards, getBillBoardById, updateBillBoard, deleteBillBoard } = require("../controller/billBoardController");
const { upload } = require("../config/cloudinary");
const router = express.Router();
// router.post("/createbillboards", upload.array("billboard_images", 5), createBillBoard);
router.post("/createbillboards", createBillBoard);
router.get("/getbillboards", getBillBoards);
router.get("/getbillboards/:id", getBillBoardById);
router.put("/updatebillboards/:id", upload.array("billboard_images", 5), updateBillBoard);
router.delete("/deletebillboards/:id", deleteBillBoard);
module.exports = router;
